### ISSUE TITLE
Console input box is not visible in videos

### ISSUE THREAD

**Issue by nymkappa** [udacity/blockchain-nanodegree-issues#108]
In the lesson 4 "Blockchain Data", most of the console log input command are not visible in the video...

As you can see in this screenshot, we can't see the command input area at the bottom. https://imgur.com/a/uzRkFWr

We should see something like this instead. https://imgur.com/a/mAzrIpr

I've noticed this issue in all "Create a Transaction: Step XX".

**Comment by jperera84** [comment]
Thanks for the feedback @jorisvial the team will check on this one.

**Comment by ralhanr** [comment]
The command to enter comes up on the screen at that time while the instructor is entering it in the window, and stays on the screen for them to see...since this software just did not allow to capture that part in the recording screen.

In-fact to make it even clearer, the instructor specifically says in the video, "Since you might not see that part of the screen, so I am going to have the command on the screen for you to see right now".
