### ISSUE TITLE
File name mismatch in Blockchain Data -> Project: Private Blockchain -> 4. Step 2: Modify Functions to Persist Data

### ISSUE THREAD

**Issue by liamseanbrady** [udacity/blockchain-nanodegree-issues#151]
On this page it says "As discussed in Step 1, levelSandbox.js file…", however in https://github.com/udacity/nd1309-work-code/tree/master/Course_Blockchain_Data/Project_2_es6_starter_code, the file is actually named 'LevelSandbox.js'.

Hopefully that's helpful

Link to page: https://classroom.udacity.com/nanodegrees/nd1309/parts/31b86083-85e4-43ae-b154-6905b461f2c1/modules/0af5bc78-b446-4b60-b9cd-8659536cd59f/lessons/1abdf0a2-f349-4876-9434-77e7588cc762/concepts/03f7e2ec-f02a-4959-bd09-46f225abf4c0#

Thanks!

**Comment by jperera84** [comment]
About this, the problem is that the project instructions files name is based on the first boilerplate code provided, I added a note on Step 1 to avoid confusions:
`
**Note**: In the project instructions, the file name used can be slightly different between the 2 boilerplate code provided, just to avoid confusions the instructions described in each step are based on the first boilerplate code files name.`
